ASCIIDOC_BACKEND = "html"
DEFAULT_DATE = "fs"
DEFAULT_LANG = "fr"
OUTPUT_PATH = "./niamtokik.github.io_dev"
OUTPUT_RETENTION = [".git", ".gitignore"]
PATH = "./website"
PLUGINS = ["asciidoc_reader"] 
PLUGIN_PATHS = ["./pelican-plugins"]
RELATIVE_URLS = True
SITENAME = "-- Explicit Programming"
SITESUBTITLE = "Questions, Answers and Reflexions."
THEME = "./niamtokik-theme"
