= Entreprendre, retour d'expérience

:date:	   2010-10-03 10:20
:modified: 2010-10-04 18:40
:tags:	   	      
:category: entreprise
:authors:  Mathieu Kerjouan
:summary:  Retour d'expérience sur la création d'entreprise en France

== Introduction

Après plus d'un an en tant qu'indépendant, il est grand temps de faire
un point. Ces derniers mois passés ont été très instructif, peut-être
trop même.

== Détruire les idées reçues

Nous avons tous tendance à avoir peur de l'inconnu, peur d'agir, peur
de s'investir et surtout peur de prendre des risques. La peur de
l'entreprenariat est légitime, il n'est pas évident pour tout le monde
de sortir de sa zone de confort. Le salarié à des horaires fixes, des
protections sociales, un salaire, des congés payés et des
responsabilités limités par son contrat de travail.

Quant à lui, l'entrepreneur est «libre». Je met libre entre guillemet
car la liberté n'existe pas réellement. L'entrepreneur a lui aussi des
comptes à rendre, que ce soit à l'état via les impots, via les
investisseurs ou partenaires (si il en a) ou tout simplement à
lui-même. Un entrepreneur n'a pas réellement d'horaire, d'ailleurs, il
n'a pas réellement de salaire non plus. Il est entièrement dépendant
de ses ventes, de ses produits, de son marché ou encore de ses
clients. Il est dépendant du modèle économique qu'il a créé et des
chiffres qu'il produit.

Commençons par le commencement. Avant d'en arriver là, avant d'avoir
sa structure et les responsabilités qui en découle, il est nécessaire
d'avoir une idée et au moins l'envie de transformer cette idée en
quelque chose de réel et de concret. Tout le monde a des idées à
longueur de journée, mais qui est prêt à se lancer corps et âmes pour
concrétiser cette idée?

Transformer son idée en concept, c'est avant tout la
chiffrer. Malheureusement; cette étape, quand vous commencez, est
assez complexe. Tout d'abord, arrêtons ici le mythe: un modèle
économique se change, et évolue en fonction des besoins. Tout comme
votre idée va changer, évoluer.

Durant mon année d'expérience j'ai eu l'impression d'être un peu comme
un forgeron. Le travail d'un forgeron est long et complexe. La
création d'un couteau nécessite de nombreuses étapes. Tout d'abord le
type de couteau, qui pourrait être comparé à notre idée de base. Notre
couteau peut avoir différentes formes de lames, être pliant, avoir un
manche en bois ou être purement décoratif. Implicitement, nous avons
déjà commencé à chiffrer la valeur de notre idée. Un couteau brut,
sans manche, sans décoration, tout en métal, coutera moins cher qu'un
couteau décoratif avec un manche en ivoire.

Tout comme l'entrepreneur, le forgeron va travailler son idée,
réfléchir sur l'agencement des éléments, du coût et des éventuels
problèmes qu'il pourrait rencontrer. Le forgeron va peut-être utilisé
des méthodes qu'il n'a jamais utilisé, faire une lame en Damas par
exemple. Il va alors de voir s'entrainer. Le création d'entreprise va
devoir faire pareil. Il n'est pas plus fort qu'un autre et va devoir
tester son idée, questionner les gens, rencontrer les futurs
clients. Cette étape va permettre de relativiser. Le créateur va
devoir apprendre à accepter la critique, à modifier ses plans.

Cette étape est habituellement réalisé au cours d'une mission en tant
que salarié, la sécurité de l'emploi permet de réfléchir sereinement
sur son idée. Jusqu'au moment où on a vraiment envie d'aller plus
loin. Est-ce que cette idée pourrait nous faire vivre? Est-ce que je
pourrais rajouter ma pierre à l'édifice? Le moment du test sur le
terrain est arrivé.

Le forgeron achète sa matière première, brute, en quantité suffisante
pour faire ses essais. L'entrepreneur prend sur lui et regarder ses
économies, regarde ses droits (chomage, ACCRE, société innovante et
compare les différents modèles qu'il pourrait utiliser pour pouvoir
voir si il peut effectivement devenir son propre patron. Cette période
prends plus ou moins de temps selon les personnes, pour moi, ce fut
assez bref, 2ans d'allocation chômage? Je me lance. Qui vivra verra.

Le choix du statut est important, vu que tout le monde en parle! Pour
faire simple: non. Qui vous dit que vous êtes adapté à ce nouveau mode
de vie? Ne jouez pas les malins. Si vous êtes jeune et célibataire,
pourquoi pas. Si vous commencez à avoir de la bouteille, mettez de
côté l'idée de quitter définitement le monde du salariat.

Durant cette période d'expérience, de nombreuses personnes ont essayé
de me définir ce que c'est qu'être entrepreneur. J'ai eu le droit à la
falaise, à la solitude, au tremplin et à tout un tas de parabole plus
ou moins bien ficelés. Pour ma part, étant prudent de nature, je
pourrais dire que c'est plus une piscine, ou peut-être bien la mer ou
un océan.

Quand on arrive devant, les vagues sont calmes, il fait beau. On
regarde quand même si il y a d'autres personnes dans l'eau, et on se
rend compte rapidement que tout le monde est sur la plage, les doigts
de pieds en éventails. Quelques intrépides se mouillent le
maillot. Par sécurité, testons l'eau du bout des pieds. Elle est quand
même un peu froide! Allons-y progressivement...

Les changements brusques ne sont pas supportés par tout le monde,
certains les acceptes très bien, d'autres font un rejet ferme et
définitif. Aujourd'hui, de nombreuses solutions permettent de se
tester. Le portage salarial, les Coopérative d'Activité et d'Emploi
(CAE), ou encore le statut d'auto-entrepreneur, permettent d'avoir un
aperçu de ce qu'est cette aventure.

Le portage salarial est un modèle très intéressant. Vous continuez
d'être salarié, vous continuez d'avoir vos droits, tout en profitant
du SIRET d'une structure plus grande. Le portage salarial vous permet
de tester votre activité en toute sécurité. De plus, la plupart des
sociétés faisant du portage salarial propose des rencontres entre
membres et donnent des formations... Ce qui permet de se remettre à
niveau ou d'apprendres de nouvelles choses. En contre partie, la
société récupère un pourcentage de votre chiffre d'affaire, permettant
de payer la comptabilité et les différents services qu'ils vous
fournissent.

La Coopérative d'Activité et d'Emploi est similaire au portage
salarial, sauf qu'elle se veut plus généraliste et n'est pas
spécialisé dans un domaine en particulier. Elle permet de mutualiser
les ressources entre les membres et de tester son activité via un
contrat CAPE (Contrat d'Appui au Projet d'Entreprise). Ce contrat vous
permet de recevoir vos allocations chômages tout en travaillant pour
des clients. Les profits engendré sont alors mis de côté jusqu'au
moment où vous n'avez plus d'aide. Évidemment, il est possible
d'échelonner les aides, par exemple, de diminuer les aides de l'état
pour les étaler sur le long terme tout en prennant une partie de votre
profit.

L'auto-entrepenariat est un modèle batard. Il n'a pas été conçu pour
que vous soyez autonome avec mais que vous puissiez faire un travail
supplémentaire à côté de votre travail principal. Admettons que votre
passions soit de faire de la dentelle, et que votre grand-mère ainsi
que toute ses copines soient dingues de vos créations. Vous pouvez
alors monétiser votre activité légalement. Par ailleurs, cette
structure ne vous donne pas réellement de sécurité et peut vous mettre
dans l'embarrat. Si vous gagnez plus qu'une certaine somme, vous
passez instantannément à un statut de micro-entreprise, ce qui n'est
pas du tout le même monde. 

== Quelques règles

 * accepter la critique
 * cacher son ego
 * être indulgent
 * être humble
 * apprendre à dire non
 * 